### ISSUE TITLE
How do you specify the file and template under the usage section?

### ISSUE THREAD

**Issue by ginhiki** [Misterio77/flavours#10]
Some sort of example would be helpful

**Comment by Misterio77** [comment]
Hi!
Here's an example for i3wm:
```
[[item]]
file = '~/.config/i3/config'
template = 'i3'
subtemplate = 'colors'
hook = 'i3-msg reload'
rewrite = false
```

Just make a `[[item]]` for each file you want, then specify the file and template (optionally subtemplate too) with `file`, `template` and `subtemplate` keys.

If you want a list of schemes and templates, take a look at the [base16 repo](https://github.com/chriskempson/base16).

**Comment by Misterio77** [comment]
Here's how config.toml looks like in my dotfiles: https://github.com/Misterio77/dotfiles/blob/master/home/.config/flavours/config.toml

**Comment by Misterio77** [comment]
Closing this as an possible documentation improvement, centralized in #11.

Let me know if you need any more help
