### ISSUE TITLE
qutebrowser hook issue

### ISSUE THREAD

**Issue by loiccoyle** [Misterio77/flavours#12]
I was trying out `flavours` but I have run into a problem.

I want to reload `qutebrowser` here is the relevant part of the config:
```ini
[[item]]
file='$XDG_CONFIG_HOME/qutebrowser/colours.py'
template='qutebrowser'
subtemplate='minimal'
rewrite=true
hook='pgrep -x qutebrowser && qutebrowser :config-source'
```

But unfortunately qutebrowser does not reload. If I run the hook command in a terminal it works fine. if I remove the pgrep part and use:
```ini
hook='qutebrowser :config-source'
```
it also works but causes issues (not related to `flavours`) when qutebrowser is not running.

Note that `flavours` does not print out an error message.

**Comment by Misterio77** [comment]
Hey!

I did the hook functionality a few months ago, but as far as i tried, i couldn't make it work like an actual shell command. It pretty much runs the first word as the command and the rest as an argument.

The only way i can think of to make this run in a shell but still be cross platform will be adding a config file in the future that will allow the user to specify the shell path.

So, long story short, the hook can be just one command and its arguments, not an bash/sh/other shell expression.

Try running it inside bash, like this:
`hook='bash -c "pgrep -x qutebrowser && qutebrowser :config-source"'

**Comment by loiccoyle** [comment]
Thanks that did the trick. Maybe it's worth mentioning this somewhere. Have a great day!

**Comment by Misterio77** [comment]
Thanks for the input! Will add a heads up to the README.

Really excited to see other people using this. I plan on doing some sort of user gallery, so feel free to send me a pic of your desktop if you're willing to share it <3
