### ISSUE TITLE
Getting an Error On Some JPEGs "Invalid JPEG Format: SOI is not an SOI Marker"

### ISSUE THREAD

**Issue by jacksonSingleton** [Misterio77/flavours#13]
Happens when running `flavours generate dark ./image-name.jpg` From what I can gather it's coming from the image-rs library. Not really sure what I can do to fix.

**Comment by Misterio77** [comment]
Hey, nice catch!
I did get that warning from one specific image in my library, i think.
Does the scheme still generate? In my case i'm pretty sure it does.
Could you possibly send me the image, as well? Maybe some specific color profile or something like that causes it

**Comment by Misterio77** [comment]
Maybe this was fixed in #22?
