### ISSUE TITLE
Create caches of generated colorschemes for faster switching

### ISSUE THREAD

**Issue by gingkapls** [Misterio77/flavours#17]
Right now flavours recreates the colour schemes from files afresh every time the generate command is called.

If we could store the generated colour scheme in a folder (perhaps in the same folder as other colour schemes or in $HOME/.cache/<somefolder>) and then when that same file is used to generate a colour scheme, using the pre-generated one instead of generating a new one would cut some of the workload and thus resulting time I guess.

**Comment by Misterio77** [comment]
Hey.

That's something i actually considered when implementing the generate subcommand. But i think it leaves up a few too many details which would be a little counterintuitive to use. It's actually pretty simple to do in bash, and i think it fits better as something we leave up to the user to do on their workflow.
Here's a simple wayto do it in bash:

```bash
wallpaper=$1

flavours info generated-$wallpaper || flavours generate dark $wallpaper -s generated-$wallpaper
flavours apply generated-$wallpaper
```

**Comment by Misterio77** [comment]
I'm closing this for now, but feel free to reopen if you ever come with a new ideia on this matter
