### ISSUE TITLE
Option to list all available templates, not only schemes

### ISSUE THREAD

**Issue by devhell** [Misterio77/flavours#35]
Hi,

First of all, thank you so much for this wonderful tool. It's made my life a lot easier and its design is fantastic!

I'm not sure if I'm just not seeing it, but is there a way to easily list available templates? Listing schemes is not an issue of course, but when I want to check which apps are supported I find myself having to look in `~/.local/share/flavours/templates/`. Is there a way of listing templates directly in `flavours`, and if not, would you consider it for future versions?

Thank you again!

**Comment by Misterio77** [comment]
Thanks a lot for your kind words!

As of now, there's not a command implemented for listing templates, but i for sure can implement one soon(ish).

**Comment by Misterio77** [comment]
Fixed by #67. Feel free to reopen if needed!

**Comment by devhell** [comment]
Thanks again, @Misterio77 and @probably-neb, this is awesome, can't wait for it to land in nixpkgs. :smile:
