### ISSUE TITLE
Provide a default config for each template.

### ISSUE THREAD

**Issue by lijiaqigreat** [Misterio77/flavours#42]
I think most of the config will be the same for most users. It would be nice to provide a default config, and add an "enabled" flag defaulting to false.

Or even better, defaulting the "enabled" flag to "auto" which detects whether a program exists.

**Comment by Misterio77** [comment]
Thanks for the suggestion, but I'm not sure if I'd like this. Not all programs support sourcing different config files, and writting stuff to people's config implicitly is not very nice.
