### ISSUE TITLE
Set minimum Rust Version

### ISSUE THREAD

**Issue by Quitlox** [Misterio77/flavours#44]
Hi there! First of all, great tool! I'm having a lot of fun with it. 

While installing flavours on a different machine using `cargo build` (same using the AUR package), I encountered an error.

<img src="https://user-images.githubusercontent.com/7038131/147501977-c23a8610-7072-41d8-bc2b-a77d12c35787.png">

As it turns out, just upgrading my Rust version from 1.52 to 1.57 solved the issue. 

It took me a second to figure out, since I am not experienced with Rust, and I imagine I am not the only one. Would it be an idea to set a minimum Rust version in `cargo.toml`? It seems that this is possible as of recent (rust-lang/cargo#9732).

Alternatively, I would propose to add one or two lines in the `README.md` stating upgrading as a potential fix for build errors. The latter I could do myself, the former is probably easier for someone with experience in Rust :stuck_out_tongue:.

**Comment by Misterio77** [comment]
Hey! Thank you for the report!

I'm not sure if all distros have rust `1.57` packaged, so i think i'd like to play safe and enforce `1.56`, if possible. Could you check if it compiles with `1.56`?

I think both solutions combined would work the best!
