### ISSUE TITLE
Modify sources

### ISSUE THREAD

**Issue by jocelynthode** [Misterio77/flavours#53]
Hey,

I really like using this tool as it simplifies my theme changing habit a lot. However one thing I think which could be better would be to be able specify the templates and schemes sources directly in the config.toml file.

I think it would be easier especially when initializing the tool to have them in the configuration file as it is configure IMHO instead of having to manually create all the folder arborescence in `.local/...`

I could try submitting a PR for this if you're interested although I've never writtenrrust before

Cheers

**Comment by Misterio77** [comment]
Hey, thanks for the suggestion!

I'm about to merge #48, which should help with your usecase.

I sure agree adding an option to set this on the config would also work. I think this order of precedence makes sense: config file -> sources file in `.config` -> sources file in `.local/share`

A PR would be very welcome :)

**Comment by Misterio77** [comment]
I think this was fixed by https://github.com/Misterio77/flavours/pull/62, feel free to reopen if there's anything missing!
