### ISSUE TITLE
Publish package on Homebrew

### ISSUE THREAD

**Issue by augustebaum** [Misterio77/flavours#63]
Hi,

I love `flavours`, thanks so much!
Would it be possible to have it available from Homebrew?

Let me know if I can be of any help.

**Comment by Misterio77** [comment]
Hello! Thanks a lot for your kind words.

I'd love to get flavours on Homebrew. I'm reading up on how to package it, so I might get a package going in the next couple of days.

If you have the time, please do feel free to write a formula and open up a PR to add it on homebrew/homebrew-core!

**Comment by awanwar** [comment]
I've opened a PR for this on [homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/126698).
