### ISSUE TITLE
AUR package cannot find templates in config path

### ISSUE THREAD

**Issue by probably-neb** [Misterio77/flavours#64]
Hello, I've been playing around with flavours for a couple hours now and It's pretty great. I've been having trouble getting it to recognize my custom schemes and templates in my .config/flavours directory. I cloned it to my machine and was playing around with it looking for a bug and ... couldn't find one? The cloned version works just fine. Both the outputs are shown below
#### using `/usr/bin/flavours` installed through aur:
```
❱ flavours apply nord
Error: Couldn't read template i3/nebi3 at "/home/neb/.local/share/flavours/base16/templates/i3/templates/nebi3.mustache". Check if the correct template/subtemplate was specified, and run the update templates command if you didn't already.

Caused by:
    No such file or directory (os error 2)
```
#### using local build & `cargo run`:
```
❱ cargo run -- apply nord
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/flavours apply nord`
Some("/home/neb/.config/flavours/templates/i3/templates/nebi3.mustache"), Is_file: true
Some("/home/neb/.config/flavours/templates/nvim/templates/default.mustache"), Is_file: false
Some("/home/neb/.config/flavours/templates/kitty/templates/default.mustache"), Is_file: false
```
_the extra "is_file" lines were my attempts at debugging it's the only change I've made to the code_

I double checked if it was recognizing my config file as shown: 
```
❱  flavours -v
Using directory: "/home/neb/.local/share/flavours"
Using config file: "/home/neb/.config/flavours/config.toml"
```
I'm at a loss for why these two builds would be different, and why only the AUR build would be unable to recognize the templates and schemes directories in my .config. Hoping you might have some insights
thanks!

**Comment by Misterio77** [comment]
Hey!

IIRC, the AUR version is using a tagged release, while the feature that allows you to put schemes and templates in `.config` hasn't been part of a relase yet.

I think we're good for a tag now, I'll get it going

**Comment by probably-neb** [comment]
thanks!

**Comment by probably-neb** [comment]
Thanks for fixing it so fast!
