### ISSUE TITLE
HSL not supported by the builder?

### ISSUE THREAD

**Issue by Adhalianna** [Misterio77/flavours#73]
I have tried using values like `{{base09-hsl-h}}` in one of my templates and it seems not to work while `{{base09-rgb-r}}` and `{{base09-hex}}` get substituted in the same template. According to [base16 builder spec](https://github.com/chriskempson/base16/blob/main/builder.md) the HSL values should be supported too. 

My flavours version:
```sh
flavours -V
flavours 0.6.1
```

**Comment by Misterio77** [comment]
I believe this has been fixed by https://github.com/Misterio77/flavours/pull/76. Feel free to reopen if there's anything missing!
