### ISSUE TITLE
Replace between start and end no longer works with version 0.7.0

### ISSUE THREAD

**Issue by tbethe** [Misterio77/flavours#78]
Every singe item in my flavours config that does not use a full rewrite but a replace between `start` and `end` no longer works.

Parsing the `start` and `end` is not an issue, but when it writes back the new scheme, a newline is omitted, meaning that the following is written: 

```
# Start flavours

(omitted)

    - { index: 19, color: '0xe0ccd1' }
    - { index: 20, color: '0x665055' }
    - { index: 21, color: '0x42383a' }# End flavours
```

The next time I run `flavours apply` it cannot find he `end`.

**Comment by Misterio77** [comment]
Should be fixed in v0.7.1
